name: Trigger Step Function CI/CD

on:
  push:
    paths:
      - 'step-functions/**'

jobs:
  trigger-step-function:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Trigger Step Function
      run: |
        aws stepfunctions start-execution \
          --state-machine-arn arn:aws:states:us-east-1:${{ secrets.AWS_ACCOUNT_ID }}:stateMachine:MLPipelineStateMachine \
          --input '{}'
